src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;

#[ORM\Entity(repositoryClass: UserRepository::class)]
#[ORM\Table(name: '`user`')]
#[UniqueEntity(fields: ['email'], message: 'There is already an account with this email')]
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'string', length: 180, unique: true)]
    private $email;

    #[ORM\Column(type: 'json')]
    private $roles = [];

    #[ORM\Column(type: 'string')]
    private $password;

    #[ORM\Column(type: 'string', length: 255)]
    private $lastname;

    #[ORM\Column(type: 'string', length: 255)]
    private $firstname;

    #[ORM\Column(type: 'date', nullable: true)]
    private $birthdate;

    #[ORM\Column(type: 'string', length: 10, nullable: true)]
    private $phone;

    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    private $genre;

    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    private $githubId;

    #[ORM\Column(type: 'boolean', nullable: true)]
    private $newsletter;

    #[ORM\Column(type: 'boolean', nullable: true)]
    private $Emailing;

    #[ORM\OneToMany(mappedBy: 'user', targetEntity: Annonce::class)]
    private $annonces;

    public function __construct()
    {
        $this->annonces = new ArrayCollection();
    }


    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getLastname(): ?string
    {
        return $this->lastname;
    }

    public function setLastname(string $lastname): self
    {
        $this->lastname = $lastname;

        return $this;
    }

    public function getFirstname(): ?string
    {
        return $this->firstname;
    }

    public function setFirstname(string $firstname): self
    {
        $this->firstname = $firstname;

        return $this;
    }

    public function getBirthdate(): ?\DateTimeInterface
    {
        return $this->birthdate;
    }

    public function setBirthdate(?\DateTimeInterface $birthdate): self
    {
        $this->birthdate = $birthdate;

        return $this;
    }

    public function getPhone(): ?string
    {
        return $this->phone;
    }

    public function setPhone(?string $phone): self
    {
        $this->phone = $phone;

        return $this;
    }

    public function getGenre(): ?string
    {
        return $this->genre;
    }

    public function setGenre(?string $genre): self
    {
        $this->genre = $genre;

        return $this;
    }

    public function getGithubId(): ?string
    {
        return $this->githubId;
    }

    public function setGithubId(?string $githubId): self
    {
        $this->githubId = $githubId;

        return $this;
    }

    public function isNewsletter(): ?bool
    {
        return $this->newsletter;
    }

    public function setNewsletter(?bool $newsletter): self
    {
        $this->newsletter = $newsletter;

        return $this;
    }

    public function isEmailing(): ?bool
    {
        return $this->Emailing;
    }

    public function setEmailing(?bool $Emailing): self
    {
        $this->Emailing = $Emailing;

        return $this;
    }

    /**
     * @return Collection<int, Annonce>
     */
    public function getAnnonces(): Collection
    {
        return $this->annonces;
    }

    public function addAnnonce(Annonce $annonce): self
    {
        if (!$this->annonces->contains($annonce)) {
            $this->annonces[] = $annonce;
            $annonce->setUser($this);
        }

        return $this;
    }

    public function removeAnnonce(Annonce $annonce): self
    {
        if ($this->annonces->removeElement($annonce)) {
            // set the owning side to null (unless already changed)
            if ($annonce->getUser() === $this) {
                $annonce->setUser(null);
            }
        }

        return $this;
    }

}

src/Controller/UsersController.php
<?php

namespace App\Controller;

use App\Form\EditNewsletterType;
use App\Form\EditProfileType;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class UsersController extends AbstractController
{
    #[Route('/users', name: 'app_users')]
    public function index(): Response
    {
        return $this->render('users/index.html.twig', [
            'controller_name' => 'UsersController',
        ]);
    }

    #[Route('/users/newsletter', name: 'app_users_newsletter')]
    public function shownewsletter(Request $request, EntityManagerInterface $entityManager): Response
    {
        $user = $this->getUser();
        $form = $this->createForm(EditNewsletterType::class, $user);

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($user);
            $entityManager->flush();

            $this->addFlash('message', 'Mise a jour !');
            return $this->redirectToRoute('app_users');
        }

        return $this->render('users/newsletter.html.twig', [
            'registrationForm' => $form->createView(),
        
        ]);
    }

    #[Route('/users/edit', name: 'app_users_edit')]
    public function editProfile(Request $request, EntityManagerInterface $entityManager)
    {
        $user = $this->getUser();
        $form = $this->createForm(EditProfileType::class, $user);

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($user);
            $entityManager->flush();

            $this->addFlash('message', 'Mise a jour !');
            return $this->redirectToRoute('app_users');
        }

        return $this->render('users/edit.html.twig', [
            'registrationForm' => $form->createView(),
        ]);
    }
    
}

templates/users/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Best Deals - Modifier le profile{% endblock %}

{% block body %}
<div class="container-fluid">
    <div class="row flex-nowrap">
        <div class="col-auto col-md-3 col-xl-2 px-sm-2 px-0 bg-white rounded-end">
            <div class="d-flex flex-column align-items-center align-items-sm-start px-3 pt-2 text-dark min-vh-100">
              <a class="d-flex align-items-center pb-3 mb-md-0 me-md-auto text-black text-decoration-none">
                <span class="fs-5 d-none d-sm-inline arvos">Profile</span>
              </a>
              <ul class="nav nav-pills flex-column mb-sm-auto mb-0 align-items-center align-items-sm-start" id="menu">
                <li>
                  <a href="{{path('app_users')}}" class="nav-link px-0 align-middle text-dark">
                    <i class="fa-regular fa-user fa-lg"></i> <span class="ms-1 d-none d-sm-inline">Mon
                      Compte</span></a>
                </li>
                <li>
                  <a href="{{path('app_users_newsletter')}}" class="nav-link px-0 align-middle text-dark">
                    <i class="fa-regular fa-envelope fa-lg"></i> <span class="ms-1 d-none d-sm-inline">Newsletter</span> </a>
                </li>
                {% if is_granted('ROLE_ADMIN') %}
                <li>
                  <a href="{{path('admin')}}" class="nav-link px-0 align-middle text-dark">
                    <i class="fa-solid fa-shield fa-lg"></i> <span class="ms-1 d-none d-sm-inline">Admin</span> </a>
                </li>
                {% endif %}
              </ul>
            </div>
          </div>
        <div class="col py-3">
            <h1 class="arvos">Modifier votre profile</h1>
            <div class="container bg-white border rounded">
                {{ form_start(registrationForm) }}
                <div class="mt-4">
                    {{ form_row(registrationForm.lastname,{
                    label: 'Nom',
                }   
                    )}}
                </div>
                {{ form_row(registrationForm.firstname,{
                    label: 'Prenom',
                }  )}}
                {{ form_row(registrationForm.phone,{
                    label: 'Téléphone',
                }  )}}
                {{ form_row(registrationForm.birthdate,{
                    label: 'Anniversaire',
                }  )}}
                <div class="d-grid gap-2 col-6 mx-auto mt-4 mb-4">
                    <button type="submit" class="btn border border-3 rounded-pill">Enregistrer</button>
                </div>
                {{ form_end(registrationForm) }}
           
            </div>

        </div>
    </div>
</div>
{% endblock %}

templates/users/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Best Deals - Profile{% endblock %}

{% block body %}
<div class="container-fluid">
  <div class="row flex-nowrap">
    <div class="col-auto col-md-3 col-xl-2 px-sm-2 px-0 bg-white rounded-end">
      <div class="d-flex flex-column align-items-center align-items-sm-start px-3 pt-2 text-dark min-vh-100">
        <a class="d-flex align-items-center pb-3 mb-md-0 me-md-auto text-black text-decoration-none">
          <span class="fs-5 d-none d-sm-inline arvos">Profile</span>
        </a>
        <ul class="nav nav-pills flex-column mb-sm-auto mb-0 align-items-center align-items-sm-start" id="menu">
          <li>
            <a href="{{path('app_users')}}" class="nav-link px-0 align-middle text-dark">
              <i class="fa-regular fa-user fa-lg"></i> <span class="ms-1 d-none d-sm-inline">Mon
                Compte</span></a>
          </li>
          <li>
            <a href="{{path('app_users_newsletter')}}" class="nav-link px-0 align-middle text-dark">
              <i class="fa-regular fa-envelope fa-lg"></i> <span class="ms-1 d-none d-sm-inline">Newsletter</span> </a>
          </li>
          {% if is_granted('ROLE_ADMIN') %}
          <li>
            <a href="{{path('admin')}}" class="nav-link px-0 align-middle text-dark">
              <i class="fa-solid fa-shield fa-lg"></i> <span class="ms-1 d-none d-sm-inline">Admin</span> </a>
          </li>
          {% endif %}
        </ul>
      </div>
    </div>
    <div class="col py-3">
      <h1 class="arvos">Bonjour {{app.user.firstname}}.</h1>
      <div class="card-body bg-white rounded shadow p-3 mb-5 bg-body rounded">
        <div class="row">
          <div class="col-sm-3">
            <p class="mb-0">Nom</p>
          </div>
          <div class="col-sm-9">
            <p class="text-muted mb-0">{{app.user.lastname}}</p>
          </div>
        </div>
        <hr>
        <div class="row">
          <div class="col-sm-3">
            <p class="mb-0">Prenom</p>
          </div>
          <div class="col-sm-9">
            <p class="text-muted mb-0">{{app.user.firstname}}</p>
          </div>
        </div>
        <hr>
        <div class="row">
          <div class="col-sm-3">
            <p class="mb-0">Email</p>
          </div>
          <div class="col-sm-9">
            <p class="text-muted mb-0">{{app.user.email}}</p>
          </div>
        </div>
        <hr>
        <div class="row">
          <div class="col-sm-3">
            <p class="mb-0">Téléphone</p>
          </div>
          <div class="col-sm-9">
            <p class="text-muted mb-0">{{app.user.phone}}</p>
          </div>
        </div>
        <hr>
        <div class="row">
          <div class="col-sm-3">
            <p class="mb-0">Genre</p>
          </div>
          <div class="col-sm-9">
            <p class="text-muted mb-0">{{app.user.genre}}</p>
          </div>
        </div>
      </div>
      <button class="btn border border-3 rounded-pill float-right">
        <a class="text-decoration-none text-white" href="{{path('app_users_edit')}}">Modifier</a>
      </button>
    </div>
  </div>
</div>
{% endblock %}

templates/users/newsletter.html.twig
{% extends 'base.html.twig' %}

{% block title %}Best Deals - Newsletter{% endblock %}

{% block body %}
<div class="container-fluid">
    <div class="row flex-nowrap">
        <div class="col-auto col-md-3 col-xl-2 px-sm-2 px-0 bg-white rounded-end">
      <div class="d-flex flex-column align-items-center align-items-sm-start px-3 pt-2 text-dark min-vh-100">
        <a class="d-flex align-items-center pb-3 mb-md-0 me-md-auto text-black text-decoration-none">
          <span class="fs-5 d-none d-sm-inline arvos">Profile</span>
        </a>
        <ul class="nav nav-pills flex-column mb-sm-auto mb-0 align-items-center align-items-sm-start" id="menu">
          <li>
            <a href="{{path('app_users')}}" class="nav-link px-0 align-middle text-dark">
              <i class="fa-regular fa-user fa-lg"></i> <span class="ms-1 d-none d-sm-inline">Mon
                Compte</span></a>
          </li>
          <li>
            <a href="{{path('app_users_newsletter')}}" class="nav-link px-0 align-middle text-dark">
              <i class="fa-regular fa-envelope fa-lg"></i> <span class="ms-1 d-none d-sm-inline">Newsletter</span> </a>
          </li>
          {% if is_granted('ROLE_ADMIN') %}
          <li>
            <a href="{{path('admin')}}" class="nav-link px-0 align-middle text-dark">
              <i class="fa-solid fa-shield fa-lg"></i> <span class="ms-1 d-none d-sm-inline">Admin</span> </a>
          </li>
          {% endif %}
        </ul>
      </div>
    </div>
        <div class="col py-3">
            <h1 class="arvos">Newsletter</h1>
            <div class="container bg-white border rounded d-flex justify-content-center">
                {{ form_start(registrationForm) }}
                <div class="mt-4">
                    {{ form_row(registrationForm.newsletter,{
                     label: 'Souhaitez vous activer les newsletters.',
                type: 'newsletter',
                row_attr: {
                    class: 'form-switch h5'
                }  
                })}}

                </div>
                <div class="mb-4">
                    {{ form_row(registrationForm.emailing,{
                    label: 'Souhaiter vous recevoir des emails promotionnels',
                    row_attr: {
                        class: 'form-switch h5'
                    }  
                } )}}
                </div>
                <div class="d-grid gap-2 col-6 mx-auto mb-4">
                    <button type="submit" class="btn border border-3 rounded-pill">S'inscrire</button>
                </div>
                {{ form_end(registrationForm) }}
            </div>

        </div>
    </div>
</div>
{% endblock %}